name: Release Debian Artifacts
on: 
  push:
    branches: 
      - odfe-prod-release
jobs:
  release-deb-artifacts:
    runs-on: [ubuntu-latest]
    steps:
      - name: Install Requests
        run: pip install requests
      - name: Run Build Test Report
        run: |
          #!/usr/bin/env python
          
          print 'I am Python'
