name: Process TAR Artifacts

on:
  push:
    branches: 
      - master
jobs:
  build-es-artifacts:
    name: Build ES Artifacts
    runs-on: ubuntu-latest
    container:
      image: opendistroforelasticsearch/multijava08101112-git:v1

    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Build tar
      run: |
        #!/bin/bash -x
        set -e
        set -u
        export JAVA_HOME=/openjdk12
        export PATH=$JAVA_HOME:$PATH
        cd elasticsearch/linux_distributions
        #./opendistro-tar-build.sh
        #tar_artifact=`ls tarfiles/*.tar.gz`
        #ls -ltr tarfiles/
        #tar_checksum_artifact=`ls tarfiles/*.tar.gz.sha512`

        #aws s3 cp $tar_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/tarball/opendistro-elasticsearch/
        #aws s3 cp $tar_checksum_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/tarball/opendistro-elasticsearch/
        #aws cloudfront create-invalidation --distribution-id E1VG5HMIWI4SA2 --paths "/downloads/*"
        echo "TAR creation for ES completed"
        
  build-kibana-artifacts:
    needs: [build-es-artifacts]
    name: Build Kibana Artifacts
    runs-on: [ubuntu-latest]
    container:
        image: opendistroforelasticsearch/jsenv:v1
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build Kibana
        run: |
          #!/bin/bash -x
          cd kibana/linux_distributions 
          #sh generate-pkg.sh
          #rpm_artifact=`ls target/*.rpm`
          #tar_artifact=`ls target/*.tar.gz`
          #tar_checksum_artifact=`ls target/*.tar.gz.sha512`
          #aws s3 cp $tar_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/tarball/opendistroforelasticsearch-kibana/
          #aws s3 cp $tar_checksum_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/tarball/opendistroforelasticsearch-kibana/
          
  test-odfe-tarball:
    needs: [build-es-artifacts]
    name: Test ODFE Tarball
    runs-on: [ubuntu-16.04]
    steps:
      - uses: actions/checkout@v1
      - name: Run ODFE Tarball
        run: |
          cd elasticsearch/linux_distributions
          odfe_version=`../bin/version-info --od`
          echo $odfe_version
          
          curl https://d3g5vo6xdbdb9a.cloudfront.net/downloads/tarball/opendistro-elasticsearch/opendistroforelasticsearch-$odfe_version-.tar.gz -o opendistroforelasticsearch-$odfe_version.tar.gz
          
          tar -zxf opendistroforelasticsearch-$odfe_version.tar.gz
          cd opendistroforelasticsearch-$odfe_version
          
          ./opendistro-tar-install.sh
          
          sleep 30
          sudo cat /var/log/elasticsearch/elasticsearch.log
          curl -XGET https://localhost:9200 -u admin:admin --insecure
          
          
          
          
          
          
          
          
          
