name: Release Debian Artifacts
on: 
  push:
    branches: 
      - odfe-prod-release
jobs:
  release-deb-artifacts:
    runs-on: [ubuntu-latest]
    container:
      image: opendistroforelasticsearch/base-ubuntu
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Release Deb Artifacts
        env:
          passphrase: ${{ secrets.PASSPHRASE }}
        run: |

          #echo "deb http://repo.aptly.info/ squeeze main" | sudo tee -a /etc/apt/sources.list.d/aptly.list
          #sudo apt-get install -y gnupg1
          #sudo apt install -y gpgv1
          #alias gpg=gpg1
          #wget -qO - https://www.aptly.info/pubkey.txt | sudo apt-key add -

          #sudo apt-get update -y
          #sudo apt-get install -y aptly
          #aws s3 cp s3://opendistro-docs/github-actions/pgp-public-key .
          #aws s3 cp s3://opendistro-docs/github-actions/pgp-private-key .

          #aptly repo create -distribution=stable -component=main odfe-release

          #mkdir -p downloads/debs
          #aws s3 sync s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/debs downloads/debs
          #aptly repo add odfe-release downloads

          #aptly repo show -with-packages odfe-release
          #aptly snapshot create opendistroforelasticsearch from repo odfe-release
          #aptly snapshot list

          #gpg --import pgp-public-key
          #gpg --allow-secret-key-import --import pgp-private-key
          #echo "Printing Secret List"
          #ls -ltr ~/.gnupg/
          #gpg --list-secret

          #aptly publish snapshot -batch=true -passphrase=$passphrase opendistroforelasticsearch

          #aws s3 sync ~/.aptly/public/ s3://artifacts.opendistroforelasticsearch.amazon.com/staging/apt
          
          #aws s3 sync ~/.aptly/public/ s3://artifacts.opendistroforelasticsearch.amazon.com/apt

          #aws cloudfront create-invalidation --distribution-id E1VG5HMIWI4SA2 --paths "/staging/apt/*"
          
          #aws cloudfront create-invalidation --distribution-id E1VG5HMIWI4SA2 --paths "/apt/*"
          
  Test-ISM-Plugin:
    runs-on: [ubuntu-16.04]
    strategy:
      matrix:
        java: [12]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: opendistro-for-elasticsearch/index-management
          ref: master
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run Debian Staging Distrubution
        run: |
          sleep 20
          sudo sysctl -w vm.max_map_count=262144

          sudo add-apt-repository -y ppa:openjdk-r/ppa
          sudo apt update -y
          sudo apt install -y openjdk-11-jdk
          sudo sudo apt install -y net-tools

          wget -qO - https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch | sudo apt-key add -
          echo "deb https://d3g5vo6xdbdb9a.cloudfront.net/apt stable main" | sudo tee -a /etc/apt/sources.list.d/opendistroforelasticsearch.list

          wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.4.2-amd64.deb
          sudo dpkg -i elasticsearch-oss-7.4.2-amd64.deb

          sudo apt-get -y update
          sudo apt install -y opendistroforelasticsearch
          
          sudo chmod 777 /etc/elasticsearch/elasticsearch.yml
          sudo /usr/share/elasticsearch/bin/elasticsearch-plugin remove opendistro_security
          sudo sed -i /^opendistro_security/d /etc/elasticsearch/elasticsearch.yml
          sudo sed -i /CN=kirk/d /etc/elasticsearch/elasticsearch.yml

          sudo /etc/init.d/elasticsearch start

          sleep 30
          
          ./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200
