name: Build Kibana Docker Image

on:
  push:
    branches: 
      - kibana-docker
jobs:
  build-kibana-docker:
    runs-on: [ubuntu-16.04]
    name: Build Kibana Docker
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/checkout@v1
      - name: Build Kibana Docker
        run: |
          git branch
          sudo apt-get install python-virtualenv
          ./download_kibana_plugins.sh
          cd kibana/bin
          ODFE_VER=`./version-info --od`
          echo "ODFE VERSION $ODFE_VER"
          cd ..
          cd docker
          make build
    
