name: Webhook Build ES Docker on Dispatch
on: repository_dispatch
jobs:
  build:
    name: Build ES Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Starting ES Docker Build
      if: github.event.action == 'Build_ES_Docker'
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        echo "Executing On-demand Build for ES Docker Image"
        workdir=`pwd`
        #sudo apt-get install python-virtualenv
        #./download_plugins.sh
        #cd elasticsearch/bin
        #ODFE_VER=`./version-info --od`
        #echo "ODFE VERSION $ODFE_VER"
        #cd ..
        #cd docker
        #make build
        
        #echo "******************************"
        #echo "Login to Docker"
        #echo "******************************"
        #docker login --username $DOCKER_USER --password $DOCKER_PASS
        #docker images|grep "amazon/opendistro-for-elasticsearch" > docker_id.out
        #image_id=`awk -F' ' '{print $3}' docker_id.out`
        #echo "Docker Id is $image_id"
        #docker tag $image_id opendistroforelasticsearch/opendistroforelasticsearch:$ODFE_VER
        #docker images
        #docker push opendistroforelasticsearch/opendistroforelasticsearch:$ODFE_VER
        echo "<h2>The docker image opendistroforelasticsearch/opendistroforelasticsearch:1.4.0 for ODFE has been created and uploaded to docker-hub</h2>" >> $workdir/Release.md
        
    - name: Send Email
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Docker Image Created for Triggered Build
        body: file://Release.md
        to: sngri@amazon.com
        from: Opendistro Elasticsearch
        content_type: text/html
